### ISSUE TITLE
Image as background obscures content in Media Browser

### ISSUE THREAD

**Issue by David-S-Morgan** [Cosmic-Chatter/Exhibitera#29] opened 2024-09-12 18:53 UTC
I think this is a bug -- selecting an image to use as a background in Media Browser results in the content items being completely hidden behind the image.

**Comment by forceflow1049** [comment] 2024-09-12 21:22
@David-S-Morgan I can't reproduce this—see the attached screenshot. Can you provide any details to reproduce?

<img width="656" alt="Screenshot 2024-09-12 at 4 21 09 PM" src="https://github.com/user-attachments/assets/167129ee-ea0f-4368-accb-215f506715c4">

**Comment by David-S-Morgan** [comment] 2024-09-13 13:35
Here's a screenshot -- left side is Chromium, right side is Firefox.  (Ignore how ugly this looks -- it's very much a work in progress!)

![Screenshot from 2024-09-13 09-32-54](https://github.com/user-attachments/assets/42c879c5-4800-44e5-b969-bdb9e89789be)

**Comment by forceflow1049** [comment] 2024-09-13 15:06
Aren't browsers grand? This is good feedback and I'll see if I can track it down.

**Comment by David-S-Morgan** [comment] 2024-09-13 16:40
Heh, yes indeed.  FWIW we use Chromium for our production exhibits, so this
isn't a show stopper for us.

**Comment by forceflow1049** [comment] 2024-09-16 02:16
@David-S-Morgan this is fixed in https://github.com/Cosmic-Chatter/Exhibitera/commit/ea103b604478d1a6e95c1c825a5a895b0e15b4f3 which will be included in 5.2.

This was a really weird bug... it actually seems like it shouldn't have been working in Chromium or Webkit at all. But it even worked in Firefox until recently, because I hd to update Firefox to even be able to reproduce this.

**Closed by forceflow1049** 2024-09-16 02:16 UTC
Labels: bug, Apps, Media Browser
